services:
  frontend:
    build: ./frontend
    container_name: frontend
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    environment:
      - FRONTEND_URL=https://app.cdnproxy.top
    command: "npm run start"
    networks:
      - cdnproxy_net

  proxy-server:
    build: ./proxy-server
    container_name: proxy-server
    env_file:
      - ./proxy-server/.env
    environment:
      - NODE_ENV=production
      - PORT=8080
    command: npm start
    ports:
      - "8080:8080"
    networks:
      - cdnproxy_net

networks:
  cdnproxy_net:
    driver: bridge